#!/bin/bash

set -e

. /usr/libexec/os-helpers-logging

BINDMOUNTED_NVPMODEL_PATH="/etc/nvpmodel-config"
NVPMODEL_FILE="nvpmodel.conf"
HIGH_POWER_GPU_PG_MASK_PARAM="512"
MID_POWER_GPU_PG_MASK_PARAM="17353"
NVPMODEL_GPU_PG_MASK_FILE="/opt/nvidia/l4t-gpusetup/gpu_pg_mask"
GPU_PG_CONF_TEMP_PATH="/var/volatile/gpu_pg_mask.tmp"

current_power_mode=""
target_power_mode=""
declare -A power_modes

query_power_mode() {
    applied_power_mode=$(/usr/sbin/nvpmodel -q)
    if [[ "$applied_power_mode" == null ]] || [[ -z "$applied_power_mode" ]]; then
        fail "Power mode could not be queried!"
    else
        power_mode_name=$(echo "${applied_power_mode}" | sed -n 1p)
        power_mode_index=$(echo "${applied_power_mode}" | sed -n 2p)
        info "Current power mode: $power_mode_name"
        info "Current power mode index: $power_mode_index"

        exit 0
    fi
}

update_modprobe_files() {
    power_mode=$1

    # /opt/nvidia/l4t-gpusetup/ is read-only but is required to be writable by nvpmodel, we thus use bind-mounts
    # and redirects instead of copying them directly
    if [[ "$target_power_mode" == "0" ]] || [[ "$target_power_mode" == "1" ]]; then
        cat ${NVPMODEL_GPU_PG_MASK_FILE} | sed "s/\(gpu_pg_mask_param=\)[^ ]*/\1$HIGH_POWER_GPU_PG_MASK_PARAM/" > ${GPU_PG_CONF_TEMP_PATH}
    else
        cat ${NVPMODEL_GPU_PG_MASK_FILE} | sed "s/\(gpu_pg_mask_param=\)[^ ]*/\1$MID_POWER_GPU_PG_MASK_PARAM/" > ${GPU_PG_CONF_TEMP_PATH}
    fi

    # The two paths below are hardcoded in and used by the nvpmodel tool
    cat ${GPU_PG_CONF_TEMP_PATH} > "${NVPMODEL_GPU_PG_MASK_FILE}.tmp"
    cat "${NVPMODEL_GPU_PG_MASK_FILE}.tmp" > "${NVPMODEL_GPU_PG_MASK_FILE}"
    rm -rf ${GPU_PG_CONF_TEMP_PATH}
}

while [ "$#" -gt "0" ]; do
    key=$1
    case $key in
        -q|--query)
            query_power_mode
            ;;
        *)
            warn "[WARNING] Unknown argument '$1', ignoring"
            ;;
      esac
      shift
done

if [ -f "/etc/os-release" ]; then
    source /etc/os-release
fi

if [ -f "/usr/sbin/balena-config-vars" ]; then
        source /usr/sbin/balena-config-vars --no-cache
fi

if [[ "$OS_POWER_MODE" == null ]] || [[ -z "$OS_POWER_MODE" ]]; then
    update_bindmount=false
    if [ -e ${BINDMOUNTED_NVPMODEL_PATH}/${NVPMODEL_FILE} ]; then
        bindmount_config_md5sum=$(md5sum ${BINDMOUNTED_NVPMODEL_PATH}/${NVPMODEL_FILE} | awk '{print $1}')
        bsp_config_md5sum=$(md5sum /etc/${NVPMODEL_FILE} | awk '{print $1}')
        if [ ! "$bindmount_config_md5sum" == "$bsp_config_md5sum" ]; then
            update_bindmount=true
        else
            info "No need to update bind mounted configuration file. BSP default power mode will be used."
        fi
    else
        update_bindmount=true
    fi

    if [[ "$update_bindmount" == true ]]; then
        cat /etc/${NVPMODEL_FILE} > ${BINDMOUNTED_NVPMODEL_PATH}/${NVPMODEL_FILE}
        info "Created / updated bind mounted configuration file. BSP default power mode will be used."
    fi
else
    if [ -e ${BINDMOUNTED_NVPMODEL_PATH}/${NVPMODEL_FILE} ]; then
       current_power_mode=$(cat ${BINDMOUNTED_NVPMODEL_PATH}/${NVPMODEL_FILE} | grep "PM_CONFIG DEFAULT" | cut -d "=" -f 2 | tail -n 1 | awk '{print $1}')
    fi

    power_modes=(["low"]="3" ["mid"]="1" ["high"]="0")

    case $OS_POWER_MODE in
        low|mid|high)
            target_power_mode="${power_modes[$OS_POWER_MODE]}"
            ;;
        *)
            target_power_mode="$OS_POWER_MODE"
            ;;
    esac

    info "Requested power mode: $OS_POWER_MODE"
    info "Target power mode: $target_power_mode"
    if [[ "$target_power_mode" == "$current_power_mode" ]]; then
        info "Target power mode is already applied"
    else
        cat /etc/${NVPMODEL_FILE} | sed -e "s/\(PM_CONFIG DEFAULT=\)\(.*\)/\1${target_power_mode} >/g" > ${BINDMOUNTED_NVPMODEL_PATH}/${NVPMODEL_FILE}
        update_modprobe_files $target_power_mode
        info "Target power mode was written to the configuration file"
    fi
fi
