[Unit]
After=etc-nvpmodel\x2dconfig.mount etc-modprobe.d-nvidia\x2ddrm.conf.mount etc-modprobe.d-nvidia\x2ddrm.conf.tmp.mount
Requires=etc-nvpmodel\x2dconfig.mount etc-modprobe.d-nvidia\x2ddrm.conf.mount etc-modprobe.d-nvidia\x2ddrm.conf.tmp.mount
